# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    cas_login_target: '%env(string:CAS_LOGIN_TARGET)%'
    cas_logout_target: '%env(string:CAS_LOGOUT_TARGET)%'
    cas_host: '%env(string:CAS_HOST)%'
    cas_port: '%env(int:CAS_PORT)%'
    cas_path: '%env(string:CAS_PATH)%'
    cas_gateway: '%env(bool:CAS_GATEWAY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Security\CasAuthenticator:
        arguments:
            $config:
                host: '%env(string:CAS_HOST)%'
                path: '%env(string:CAS_PATH)%'
                port: '%env(int:CAS_PORT)%'
                ca: '%env(bool:CAS_CA)%'
                handleLogoutRequest: '%env(bool:CAS_HANDLE_LOGOUT_REQUEST)%'
                casServiceBaseUrl: '%env(string:CAS_SERVICE_BASE_URL)%'
                casLogoutTarget: '%env(string:CAS_LOGOUT_TARGET)%'
                force: '%env(bool:CAS_FORCE)%'
                gateway: '%env(bool:CAS_GATEWAY)%'
    
    
    App\Service\LdapService:
        arguments:
            $config:
                host: '%env(string:LDAP_HOSTNAME)%'
                port: '%env(int:LDAP_PORT)%'
                encryption: '%env(string:LDAP_ENCRYPTION)%'
                dn: '%env(string:LDAP_DN)%'
                password: '%env(string:LDAP_PASSWORD)%'

    App\Security\UserProvider:
        arguments:
            $entityClass: 'App\Entity\User'

    # ldap
    #Symfony\Component\Ldap\Ldap:
    #    arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
    #    tags:
    #        - ldap
    #Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
    #    arguments:
    #        -   host: "%ldap_hostname%"
    #            port: 389
    #            encryption: tls
    #            options:
    #                protocol_version: 3
    #                referrals: false


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\WimsFileObjectCreatorService:
        arguments:
            $config:
                directory_structure: '%env(resolve:DIRECTORY_STRUCTURE)%'
                directory_right: 0o775
                file_right: 0o664
                user_id:
                    regex: /^[a-z0-9]{8}$/
                grouping_classes_id:
                    min: 1000000
                    max: 9999999
                    regex: /^[1-9]\d{6}$/
                class_id:
                    regex: /^[1-9][0-9]*$/
                class_name:
                    regex: /^.{2,}$/
                structure:
                    sub_folders:
                        - 'cdt'
                        - 'def'
                        - 'doc'
                        - 'exams'
                        - 'freeworks'
                        - 'freeworksdata'
                        - 'livret'
                        - 'noscore'
                        - 'score'
                        - 'seq'
                        - 'sheets'
                        - 'src'
                        - 'tool'
                        - '.users'
                        - 'vote'
                    files:
                        - '.def'
                        - 'Exindex'
                        - 'Extitles'
                        - 'supervisor'
                        - '.userlist'
                        - 'version'
                default_template_data:
                    cas: &cas '%env(resolve:CAS)%'
                    user: &user
                        is_teacher: false
                        is_supervisor: false
                        is_student: false
                        uid: ''
                        first_name: ''
                        last_name: ''
                        email: ''
                        password: ''
                        agree_cgu: true
                        agree_sup_cgu: true
                        exists: true
                        supervisable: true
                        forcechpwd: false
                        creator: '127.0.0.1'
                    supervisor:
                        <<: *user
                        is_supervisor: true
                        first_name: '%env(resolve:SUPERVISOR_FIRST_NAME)%'
                        last_name: '%env(resolve:SUPERVISOR_LAST_NAME)%'
                        email: '%env(resolve:SUPERVISOR_EMAIL)%'
                        password: '%env(resolve:SUPERVISOR_PASSWORD)%'
                    teacher:
                        <<: *user
                        is_teacher: true
                    student:
                        <<: *user
                        is_student: true
                        agree_cgu: false
                        supervisable: false
                    structure: &structure
                        password: 'test'
                        supervisor:
                        description: 'Nom de la structure'
                        institution_name: "Nom de l'institution"
                        location: ''
                        geoloc: ''
                        lang: 'fr'
                        creation: 'now'
                        expiration: '20240915'
                        limit: 50
                        top_score:
                        super_class:
                        type:
                        level: ''
                        parent:
                        secure: 'all'
                        type_name: ''
                        cas_auth: *cas
                        auth_idp: 'cas;'
                        connections:
                        bg_color: '#f6f6f6'
                        bg_img: ''
                        score_color: '#FFFFFF,#FF0000,#FF0000,#FF0000,#FFA500,#FFA500,#FFA500,#FFFF00,#FFFF00,#00FF00,#00FF00'
                        act_color: '#000000,#CCCCFF,#99CCFF,#9999FF,#6666FF,#FFFFFF,#99CCDD,#AFB31E,#E6A493'
                        css: '-theme-'
                        logo: ''
                        logo_side: ''
                        ref_color: ''
                        ref_menu_color: ''
                        ref_button_color: ''
                        ref_button_bg_color: ''
                        ref_button_help_color: ''
                        ref_button_help_bg_color: ''
                        theme: 'standard'
                        theme_icon: 'default'
                        exo_log: 2
                        creator: '127.0.0.1'
                        defined: true
                        version: 6
                    class:
                        <<: *structure
                        description: 'Nom de la class'
                        institution_name: "Nom du groupement"
                        type: 1
                        type_name: 'class'
                    grouping_classes:
                        <<: *structure
                        description: 'Nom du groupement'
                        institution_name: "Nom de l'établissement"
                        type: 2
                        type_name: 'group'
                # Revoir cette section pour la supprimer
                teacher:
                    files_append:
                        - '.log'
                        - '.teacherlist'
                        - '.teacherlist_external'
                        - '.userlist_external'
                    files_create:
                        - '.users/{uid}'
                grouping_classes_user:
                    files_append:
                        - '.userlist'
                        - '.userlist_external'
                    files_create:
                        - '.users/{uid}'
                class_user:
                    files_append:
                        - '.log'
                        - '.userlist'
                        - '.userlist_external'
                    

                
